### ISSUE TITLE
Obtain Mina chainId from libp2p_helper IPC communication

### ISSUE THREAD

**Issue by akoptelov** [openmina/mina-network-debugger#28]
Currently debugger should be configured externally what chainId to use to decrypt PSK traffic. ChainId depends on both compile time and runtime configuration. Obtaining chainId is not trivial -- a Mina daemon should be started, and its RPC should be ready.

Instead, the debugger can obtain the chainId from the libp2p_helper IPC channel (as the field `networkId` of the message `Libp2pConfig`). This way, no additional configuration would be needed for the debugger.

@adonagy This will solve the issue you mentioned on the team meeting.

**Comment by vlad9486** [comment]
Implemented in `openmina/mina-network-debugger:28eab4dd`
